# Generated by Django 4.2.9 on 2024-03-31 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalstore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=50)),
                ('stock', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='medic',
        ),
    ]
